# grafana-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1m0s
  chart:
    spec:
      chart: grafana
      version: 8.2.3  # or latest stable version
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminPassword: "admin"
    service:
      type: LoadBalancer